### ISSUE TITLE
感谢一切开源的赛博菩萨，可以开一个捐赠入口！

### ISSUE THREAD

**Issue by sumruler** [RQLuo/MixTeX-Latex-OCR#10]
感谢开源！

**Comment by sumruler** [comment]
软件里的打赏图片二维码无法识别

**Comment by RQLuo** [comment]
真的感谢您的支持！！我已经更新了readme文件，愿意捐助的朋友可以微信赞助。我也将在后续开通github原生的赞助。

**Comment by RQLuo** [comment]
我刚刚上传了个新的版本，试图解决之前较为频发的latex语法未闭合错误，当然并没有完全的解决。我将持续优化，感谢支持，期待你持续关注！！

**Comment by sumruler** [comment]
确实会出现未闭合的问题，出现后面有end，前面没有begin的问题

**Comment by RQLuo** [comment]
新版本应该会改善！！感谢支持！！

**Comment by sumruler** [comment]
已捐赠，感谢您的开源。
刚刚测试了新版本公式识别的时候还是会有这个问题，我在typora中测试，删掉最后的\end{align*}公式就能正常显示了
![Clip_2024-08-24_11-03-26](https://github.com/user-attachments/assets/e5051efc-032e-4b53-83c8-8164a7a06e7f)
可否软件中自定义包裹公式的符号？例如用$$..$$包裹。

**Comment by RQLuo** [comment]
感谢您的捐赠，我会在后续支持$$...$$，采用align是考虑多行公式，此外可以发一下原始图片和代码吗？我目前正在参考各类失败样例以此改进完善，感谢你的帮助！！

**Comment by sumruler** [comment]
![image](https://github.com/user-attachments/assets/73afd7e0-0ff9-456e-b6dc-89d078f800a6)
![image](https://github.com/user-attachments/assets/e398b1ea-f623-4216-ab71-62c9ef403ca9)
![image](https://github.com/user-attachments/assets/96b43652-35e1-4d14-8955-a980a5e0559c)
我用了上面几张图片做测试都会出现这样的问题

**Comment by sumruler** [comment]
希望可以在软件中增加一些额外的设置项

**Comment by RQLuo** [comment]
嗯嗯 没问题 对了 \begin{align*}
    \cos \alpha + \cos \beta = 2 \cos \frac{\alpha + \beta}{2} \cos \frac{\alpha - \beta}{2} \\
\tan \alpha + \tan \beta = \frac{\sin (\alpha + \beta)}{\cos \alpha \cos \beta} \\
\sin \alpha + \sin \beta = 2 \sin - \frac{\alpha + \beta}{2} \cos \frac{\alpha - \beta}{2}
\end{align*}
typora能够渲染吗？

**Comment by RQLuo** [comment]
![image](https://github.com/user-attachments/assets/d4f4bd8a-f1a4-491c-9d96-f80bb3f95607)
此外如果截图能够有些文字，模型效果会更好，因为我是在文本穿插公式的数据上训练的。感谢你的支持！！
output：

sumuer \textit{commented 3 minutes ago}
\begin{align*}
\cos \alpha + \cos \beta = 2 \cos \frac{\alpha + \beta}{2} \cos \frac{\alpha - \beta}{2}
\end{align*}
\begin{align*}
\tan \alpha + \tan \beta - \frac{\sin (\alpha + \beta)}{\cos \alpha \cos \beta}
\end{align*}
\begin{align*}
\sin \alpha + \sin \beta = 2 \sin \frac{\alpha + \beta}{2} \cos \frac{\alpha - \beta}{2}
\end{align*}

**Comment by sumruler** [comment]
明白了，感谢

**Comment by sumruler** [comment]
> 嗯嗯 没问题 对了 \begin{align*} \cos \alpha + \cos \beta = 2 \cos \frac{\alpha + \beta}{2} \cos \frac{\alpha - \beta}{2} \ \tan \alpha + \tan \beta = \frac{\sin (\alpha + \beta)}{\cos \alpha \cos \beta} \ \sin \alpha + \sin \beta = 2 \sin - \frac{\alpha + \beta}{2} \cos \frac{\alpha - \beta}{2} \end{align*} typora能够渲染吗？

可以渲染

**Comment by RQLuo** [comment]
感谢反馈和支持！我将会在下一个版本增加$$..$$替换

**Comment by RQLuo** [comment]
已解决，感谢反馈！！
