### ISSUE TITLE
关于细节调整建议

### ISSUE THREAD

**Issue by marc-shen** [RQLuo/MixTeX-Latex-OCR#12]
使用版本为https://github.com/MosRat/MixTex-rs-GUI.git
发现问题为https://github.com/MosRat/MixTex-rs-GUI/issues/3#issue-2485015224

在经过简单测试后发现有以下问题：

1. 对大写英文字母的识别中，无法有效识别公式中的正体；
2. 英文字母O和数字0的之别准确度有待提高；
3. 希腊字母识别有误。

下两图为示例（上图为目标，下图为识别结果），注意其中的角标全部为正体，X和O均为大写英文字母，识别均有误。而小写英文字母角标的字体和内容识别均非常准确。

<img width="364" alt="361181539-bdac90da-2b97-4477-b6ec-6f361ac6d9ae" src="https://github.com/user-attachments/assets/6923f537-979f-4ce2-8857-b7deb0a1a81c">

<img width="732" alt="361181598-c8907427-c410-4635-84b0-ed81a240bc8d" src="https://github.com/user-attachments/assets/3b1e0e61-89d7-4a68-9460-07ddcd219873">

**Comment by RQLuo** [comment]
现在我只有500个真实数据，我做了一个网页版，打算用它来收集点数据去训练。
