### ISSUE TITLE
识别错误把  t   识别成   i

### ISSUE THREAD

**Issue by icemytime** [RQLuo/MixTeX-Latex-OCR#14]
在识别的时候会把  t  识别成  i
![image](https://github.com/user-attachments/assets/b5bb53ac-f2a4-41d4-b71c-8c803d9b1660)

\begin{align*}
\sum_{i=1}^{\infty} r_i = f_i - \alpha (P_{r_i-1} - P_{f_i-1}) + \varepsilon r_i = f_i - \alpha \sum_{s=1}^{\infty} \binom{s}{r_{i-s}} f_{i-s}) + \varepsilon r_i
\end{align*}
\(f_i = \beta (P_{r_i-1} - P_{f_i-1}) + \varepsilon f_i = \beta \sum_{s=1}^{\infty} \binom{s}{r_{i-s}} + \varepsilon f_i\)

**Comment by RQLuo** [comment]
现在我只有500个真实数据，我做了一个网页版，打算用它来收集点数据去训练。
