### ISSUE TITLE
rec模型，有时 实心点句号 .会被识别成 半角逗号 , 有没有什么办法？类似的情况，还有英文大小写等。O0, Ss, Xx之类近似的

### ISSUE THREAD

**Issue by nissansz** [RQLuo/MixTeX-Latex-OCR#15]
`rec模型，有时` 实心点句号 .会被识别成 半角逗号 , 有没有什么办法？类似的情况，还有英文大小写等。O0, Ss, Xx之类近似的

![image](https://github.com/user-attachments/assets/acef5816-24ad-41e1-8f11-7a6b3b0288cd)

![image](https://github.com/user-attachments/assets/b0c31597-1a1a-4458-8f35-1a219d055c6d)

**Comment by RQLuo** [comment]
之后会增加微调数据集
