### ISSUE TITLE
一些高频的识别错误

### ISSUE THREAD

**Issue by chinoll** [RQLuo/MixTeX-Latex-OCR#17]
\omega会被识别成0和\rho，如：1/omega
\varphi会被识别成\rho

**Comment by chinoll** [comment]
![6](https://github.com/user-attachments/assets/fa18af0f-51b3-431d-ba04-2af7c9804149)
![21](https://github.com/user-attachments/assets/30e19c33-a66a-412a-b5f8-f84d4d07b8c2)
样例

**Comment by RQLuo** [comment]
由微调数据引起的偏见，本来预训练之后是不会有这个问题。我已经开学了，有点忙之后再去完善的问题。
