### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by Ncare** [RQLuo/MixTeX-Latex-OCR#2]
1，在我的设备上，右键点击设置之后，无任何响应；
2，能否将公式标识符解析为$,  或者可以通过设置修改是$ 还是 \(；
3，能否考虑打包 MacOS 应用；

**Comment by RQLuo** [comment]
v1.1.2 设置有东西了
之后考虑在设置里面允许修改$，模型路径之类的
暂不考虑做macos，先做网页版

**Comment by RQLuo** [comment]
已经解决
