### ISSUE TITLE
默认行为不应该覆盖剪贴板

### ISSUE THREAD

**Issue by longisland-icetea** [RQLuo/MixTeX-Latex-OCR#4]
现在的默认行为似乎是检测到剪贴板里有图片就转换成tex，然后用它覆盖掉原来的图片，太不灵活。
把tex复制到剪贴板作为可选行为（单独设置热键或者gui按钮）会更好一些，现在的用法几乎是不可用状态。

**Comment by RQLuo** [comment]
感谢反馈，群里有朋友好像做了个跟完善的ui，我这两天重新训练了一下，现在模型可以部分支持手写了。

**Comment by liang-tian-yu** [comment]
补充一下，从ppt中复制文字也会经过mixtex识别，这种情况下基本上什么都识别不出来，导致剪贴板不可用
PowerPoint版本：Office LTSC专业增强版2021版本2108 ，试过很多ppt都能触发就不放例子了
希望顺便适配一下

**Comment by RQLuo** [comment]
已解决！！感谢反馈
