### ISSUE TITLE
深色模式下识别准确率较低

### ISSUE THREAD

**Issue by Pannta** [RQLuo/MixTeX-Latex-OCR#5]
以中文维基[泰勒级数](https://zh.wikipedia.org/wiki/%E6%B3%B0%E5%8B%92%E7%BA%A7%E6%95%B0)页面为例，在浅色模式下，公式识别正确：

![屏幕截图 2024-08-14 212226](https://github.com/user-attachments/assets/88d6b070-9d33-4b3d-ba4d-a96af05c4c61)

但是，在深色模式下，公式经常无法被正确识别：

![屏幕截图 2024-08-14 212531](https://github.com/user-attachments/assets/bcd9101f-5eb0-42ca-a44c-831be192cc07)

个人比较习惯使用夜间模式，而且使用深色模式的公式应该也不算少见，比如 3b1b 的视频，所以希望大佬能优化下深色模式下的识别率

操作系统：Windows 10
版本：MixTeX-v1.1.2 ~~（Release 里的版本号是不是标错了）~~

**Comment by RQLuo** [comment]
感谢反馈，我将在下一个模型预训练数据增强增加深色！

**Comment by RQLuo** [comment]
已经解决
