### ISSUE TITLE
对于linux的支持

### ISSUE THREAD

**Issue by newplay** [RQLuo/MixTeX-Latex-OCR#7]
想请问之后会不会加入对linux的支持或有没有这样的计划？

**Comment by RQLuo** [comment]
我之后会推出网页版

**Comment by MosRat** [comment]
可以试下这个：[Release](https://github.com/MosRat/MixTex-rs-GUI/releases/tag/app-v0.2.1-21-8f7760a)

**Comment by newplay** [comment]
感谢您

**Comment by RQLuo** [comment]
已经解决
