### ISSUE TITLE
如何训练，用于识别日文中文，韩文英文等全部字符？

### ISSUE THREAD

**Issue by nissansz** [RQLuo/MixTeX-Latex-OCR#8]
如何训练，用于识别日文中文，韩文英文等全部字符？

**Comment by RQLuo** [comment]
过几天会支持多语言版本。

**Comment by nissansz** [comment]
win10怎么安装使用

**Comment by RQLuo** [comment]
下载压缩包解压即可运行exe文件。

**Comment by nissansz** [comment]
随便ctr+c 一个图像，得到的结果如下，没看到文字

===成功加载模型===

\[
\lim_{k\to1}k/k/k/k\left(k-1\right)\left(k-1\right)\left(k-1\right)\]
===成功复制到剪切板===

\[
\lim_{k\to1}k/k/k/k\left(k-1\right)\left(k-1\right)\left(k-1\right)\]
===成功复制到剪切板===

**Comment by nissansz** [comment]
看不到识别的文字，不知道是不是操作有问题

**Comment by RQLuo** [comment]
操作演示： https://www.bilibili.com/video/BV1K8YzeaEi3

**Comment by RQLuo** [comment]
记得win+v

**Comment by nissansz** [comment]
有了这个图，结果不行
![image](https://github.com/user-attachments/assets/37c49714-f4b2-4c42-be0f-6463a815dcc3)

\begin{align*}
\frac{1}{N} \text{det} \text{dim} \text{dim} \text{dim} \text{dim} \text{dim} \text{dim} \text{dim} \text{G}\\
\end{align*}

**Comment by RQLuo** [comment]
后续我会有通用ocr模型，mixtex是专为latex 文本混合公式ocr做的

**Comment by nissansz** [comment]
这个怎么自己训练模型，替换模型？可以用paddleocr的模型，转换使用妈

**Comment by RQLuo** [comment]
可以看我的文章https://arxiv.org/abs/2406.17148

**Comment by nissansz** [comment]
看不懂。我只会paddleocr训练模型。

**Comment by qwerreqwuser** [comment]
这是两个物种

**Comment by qwerreqwuser** [comment]
完全不兼容

**Comment by nissansz** [comment]
怎么训练这个模型？然后使用？
准备crnn单行文本数据，无需坐标？即可训练？

**Comment by nissansz** [comment]
这个模型有没有办法返回每个字符的坐标？不会出现多字符或漏字符的问题？

**Comment by RQLuo** [comment]
它的输入是一张图片，输出是图片上的文字不带坐标端到端。

**Comment by nissansz** [comment]
输入也是文字不带坐标？输出也会有漏字，错字吧？

**Comment by RQLuo** [comment]
对不带坐标

**Comment by nissansz** [comment]
自己训练，可以怎么训练？

**Comment by RQLuo** [comment]
可以参考主页colab里面的教程

**Comment by nissansz** [comment]
没看到colab链接

**Comment by nissansz** [comment]
https://github.com/RQLuo/MixTeX-Latex-OCR/blob/main/MixTex_Demo.ipynb

看到了这个链接，如果在自己电脑训练，怎么安装环境？
cpu和gpu训练，速度一样？

**Comment by RQLuo** [comment]
pip install datasets accelerate

**Comment by nissansz** [comment]
pytorch等?

**Comment by RQLuo** [comment]
对 要代gpu的

**Comment by RQLuo** [comment]
应该就这三个，其余会连带安装

**Comment by nissansz** [comment]
cpu和gpu训练，速度一样？还是说gpu速度快很多？

**Comment by RQLuo** [comment]
gpu会快很多。

**Comment by RQLuo** [comment]
已经解决
